--- drivers/misc/Makefile
+++ drivers/misc/Makefile
@@ -62,3 +62,4 @@
 obj-$(CONFIG_LIVE_OC)    += live_oc.o
 obj-$(CONFIG_BLD)    += bld.o
 obj-$(CONFIG_BLX)		+= blx.o
+obj-$(CONFIG_TOUCH_WAKE)	+= touch_wake.o
