#!/system/xbin/bash


FILE=/system/media/audio/ui/shutdown.ogg

# allow over-ride to be specified in /data
if [ -r /data/misc/shutdown_sound ]; then
   FILE=`cat /data/misc/shutdown_sound`

# allow override in this specific place if above is not there
elif [ -r /data/media/audio/ui/shutdown.ogg ]; then
   FILE=/data/media/audio/ui/shutdown.ogg
fi

# play it if we can
if [ -r $FILE ]; then
   /system/bin/stagefright -a -o $FILE
fi
